"""
TicketDesk — main FastAPI application.

Endpoint summary
----------------
GET  /health                    Liveness probe for cloud load-balancers.
GET  /                          Serve the single-page web console.
POST /api/tickets               Create a ticket (status defaults to 'open').
GET  /api/tickets?status=       List tickets newest-first; optional status filter.
GET  /api/tickets/{id}          Fetch one ticket (404 if missing).
PATCH /api/tickets/{id}         Update status / priority / assignee.
DELETE /api/tickets/{id}        Delete a ticket (404 if missing).

Interactive docs auto-generated by FastAPI at /docs (Swagger UI)
and /redoc (ReDoc).
"""

from __future__ import annotations

import pathlib
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

from app.database import db_conn, init_db
from app.models import Priority, Status, TicketCreate, TicketOut, TicketUpdate

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

# __file__ is app/main.py → parent is app/ → static/ lives next to it.
_STATIC_DIR = pathlib.Path(__file__).parent / "static"


# ---------------------------------------------------------------------------
# Lifespan (replaces deprecated @app.on_event)
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Run init_db() once on startup; nothing to tear down on shutdown."""
    init_db()
    yield


# ---------------------------------------------------------------------------
# App instance
# ---------------------------------------------------------------------------

app = FastAPI(
    title="TicketDesk",
    description="Lightweight help-desk ticketing API — portfolio / DevOps demo.",
    version="1.0.0",
    lifespan=lifespan,
)

# Serve static assets (CSS, JS, images) at /static/…
# The web console itself is at "/" via the route below.
app.mount("/static", StaticFiles(directory=_STATIC_DIR), name="static")


# ---------------------------------------------------------------------------
# Health
# ---------------------------------------------------------------------------

@app.get("/health", tags=["ops"], summary="Liveness probe")
def health():
    """
    Returns {"status": "ok"}.
    Used by Docker HEALTHCHECK, k8s liveness probes, and uptime monitors.
    """
    return {"status": "ok"}


# ---------------------------------------------------------------------------
# Web console
# ---------------------------------------------------------------------------

@app.get("/", include_in_schema=False)
def index():
    """Serve the single-page web console (app/static/index.html)."""
    return FileResponse(_STATIC_DIR / "index.html")


# ---------------------------------------------------------------------------
# Tickets — helpers
# ---------------------------------------------------------------------------

def _row_to_ticket(ticket_id: int) -> TicketOut:
    """
    Fetch one row by id and return a TicketOut model.
    Raises 404 if not found.
    Called after INSERT/UPDATE to ensure the caller always gets fresh data.
    """
    with db_conn() as conn:
        row = conn.execute(
            "SELECT * FROM tickets WHERE id = ?", (ticket_id,)
        ).fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail=f"Ticket {ticket_id} not found.")
    return TicketOut(**dict(row))


def _now_iso() -> str:
    """Current UTC time as an ISO-8601 string (what we store in SQLite TEXT)."""
    return datetime.now(timezone.utc).isoformat()


# ---------------------------------------------------------------------------
# Tickets — CRUD endpoints
# ---------------------------------------------------------------------------

@app.post(
    "/api/tickets",
    response_model=TicketOut,
    status_code=201,
    tags=["tickets"],
    summary="Create a ticket",
)
def create_ticket(ticket: TicketCreate):
    """
    Create a new ticket.  Status is always 'open' on creation.
    Returns the full ticket including auto-assigned id and timestamps.
    """
    now = _now_iso()
    with db_conn() as conn:
        cursor = conn.execute(
            """
            INSERT INTO tickets
                (title, description, requester, assignee, priority, status, created_at, updated_at)
            VALUES
                (?, ?, ?, ?, ?, 'open', ?, ?)
            """,
            (
                ticket.title,
                ticket.description,
                ticket.requester,
                ticket.assignee,
                ticket.priority.value,   # store enum as plain string
                now,
                now,
            ),
        )
        new_id = cursor.lastrowid
    # Fetch *after* the connection closes and the INSERT is committed.
    # (Reading inside the same connection before commit can return stale data
    # in WAL mode when other connections are involved.)
    return _row_to_ticket(new_id)


@app.get(
    "/api/tickets",
    response_model=List[TicketOut],
    tags=["tickets"],
    summary="List tickets",
)
def list_tickets(
    status: Optional[Status] = Query(
        default=None,
        description="Filter by status.  Omit to return all tickets.",
    )
):
    """Return tickets ordered newest-first (highest id first)."""
    with db_conn() as conn:
        if status is not None:
            rows = conn.execute(
                "SELECT * FROM tickets WHERE status = ? ORDER BY id DESC",
                (status.value,),
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM tickets ORDER BY id DESC"
            ).fetchall()
    return [TicketOut(**dict(r)) for r in rows]


@app.get(
    "/api/tickets/{ticket_id}",
    response_model=TicketOut,
    tags=["tickets"],
    summary="Get one ticket",
)
def get_ticket(ticket_id: int):
    """Fetch a single ticket by id.  Returns 404 if it doesn't exist."""
    return _row_to_ticket(ticket_id)


@app.patch(
    "/api/tickets/{ticket_id}",
    response_model=TicketOut,
    tags=["tickets"],
    summary="Update a ticket",
)
def update_ticket(ticket_id: int, update: TicketUpdate):
    """
    Partially update a ticket.  Send only the fields you want to change.
    Valid fields: status, priority, assignee.
    Returns 422 if the body is empty; 404 if the ticket doesn't exist.
    """
    # model_dump(exclude_none=True) skips fields the caller didn't send
    raw: dict = update.model_dump(exclude_none=True)
    if not raw:
        raise HTTPException(
            status_code=422,
            detail="Provide at least one field to update (status, priority, or assignee).",
        )

    # Convert enum instances → their string values for SQL
    fields: dict = {
        k: (v.value if isinstance(v, (Status, Priority)) else v)
        for k, v in raw.items()
    }
    fields["updated_at"] = _now_iso()

    # Build "col1 = ?, col2 = ?" dynamically from whatever was sent
    set_clause = ", ".join(f"{col} = ?" for col in fields)
    values = list(fields.values()) + [ticket_id]

    with db_conn() as conn:
        result = conn.execute(
            f"UPDATE tickets SET {set_clause} WHERE id = ?", values
        )
        if result.rowcount == 0:
            # No rows changed → ticket doesn't exist
            raise HTTPException(status_code=404, detail=f"Ticket {ticket_id} not found.")

    return _row_to_ticket(ticket_id)


@app.delete(
    "/api/tickets/{ticket_id}",
    status_code=204,
    tags=["tickets"],
    summary="Delete a ticket",
)
def delete_ticket(ticket_id: int):
    """
    Permanently delete a ticket.
    Returns 204 No Content on success; 404 if it doesn't exist.
    """
    with db_conn() as conn:
        result = conn.execute(
            "DELETE FROM tickets WHERE id = ?", (ticket_id,)
        )
        if result.rowcount == 0:
            raise HTTPException(status_code=404, detail=f"Ticket {ticket_id} not found.")
    # 204 — return nothing
