"""
TicketDesk — main FastAPI application.

Endpoint summary
----------------
GET  /health                    Liveness probe for cloud load-balancers.
GET  /metrics                   Prometheus metrics (Phase 5 monitoring).
GET  /                          Serve the single-page web console.
POST /api/tickets               Create a ticket (status defaults to 'open').
GET  /api/tickets?status=       List tickets newest-first; optional status filter.
GET  /api/tickets/{id}          Fetch one ticket (404 if missing).
PATCH /api/tickets/{id}         Update status / priority / assignee.
DELETE /api/tickets/{id}        Delete a ticket (404 if missing).

Interactive docs auto-generated by FastAPI at /docs (Swagger UI)
and /redoc (ReDoc).
"""

from __future__ import annotations

import pathlib
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from prometheus_fastapi_instrumentator import Instrumentator
from sqlalchemy import text

from app.database import db_conn, init_db
from app.models import Priority, Status, TicketCreate, TicketOut, TicketUpdate

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_STATIC_DIR = pathlib.Path(__file__).parent / "static"


# ---------------------------------------------------------------------------
# Lifespan
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Create the DB table on startup if it doesn't exist yet."""
    init_db()
    yield


# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = FastAPI(
    title="TicketDesk",
    description="Lightweight help-desk ticketing API — portfolio / DevOps demo.",
    version="1.0.0",
    lifespan=lifespan,
)

app.mount("/static", StaticFiles(directory=_STATIC_DIR), name="static")

# Prometheus metrics exposed at /metrics
Instrumentator().instrument(app).expose(app)


# ---------------------------------------------------------------------------
# Health
# ---------------------------------------------------------------------------

@app.get("/health", tags=["ops"], summary="Liveness probe")
def health():
    """Returns {"status": "ok"} — used by Docker HEALTHCHECK and cloud probes."""
    return {"status": "ok"}


# ---------------------------------------------------------------------------
# Web console
# ---------------------------------------------------------------------------

@app.get("/", include_in_schema=False)
def index():
    return FileResponse(_STATIC_DIR / "index.html")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _row_to_ticket(ticket_id: int) -> TicketOut:
    """
    Fetch a single ticket by id and return a TicketOut model.
    Opens its own connection so it always reads committed data.
    """
    with db_conn() as conn:
        row = conn.execute(
            text("SELECT * FROM tickets WHERE id = :id"),
            {"id": ticket_id},
        ).mappings().fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail=f"Ticket {ticket_id} not found.")
    return TicketOut(**dict(row))


# ---------------------------------------------------------------------------
# Tickets — CRUD
# ---------------------------------------------------------------------------

@app.post("/api/tickets", response_model=TicketOut, status_code=201, tags=["tickets"])
def create_ticket(ticket: TicketCreate):
    """
    Create a new ticket. Status is always 'open' on creation.
    Uses RETURNING id so the same SQL works on both SQLite and PostgreSQL.
    """
    now = _now_iso()
    with db_conn() as conn:
        result = conn.execute(
            text("""
                INSERT INTO tickets
                    (title, description, requester, assignee, priority, status, created_at, updated_at)
                VALUES
                    (:title, :desc, :requester, :assignee, :priority, 'open', :now, :now)
                RETURNING id
            """),
            {
                "title":    ticket.title,
                "desc":     ticket.description,
                "requester": ticket.requester,
                "assignee": ticket.assignee,
                "priority": ticket.priority.value,
                "now":      now,
            },
        )
        new_id = result.fetchone()[0]
    # Fetch after commit so the response always reflects the persisted row
    return _row_to_ticket(new_id)


@app.get("/api/tickets", response_model=List[TicketOut], tags=["tickets"])
def list_tickets(
    status: Optional[Status] = Query(default=None, description="Filter by status.")
):
    """Return tickets ordered newest-first. Optionally filter by status."""
    with db_conn() as conn:
        if status is not None:
            rows = conn.execute(
                text("SELECT * FROM tickets WHERE status = :status ORDER BY id DESC"),
                {"status": status.value},
            ).mappings().fetchall()
        else:
            rows = conn.execute(
                text("SELECT * FROM tickets ORDER BY id DESC")
            ).mappings().fetchall()
    return [TicketOut(**dict(r)) for r in rows]


@app.get("/api/tickets/{ticket_id}", response_model=TicketOut, tags=["tickets"])
def get_ticket(ticket_id: int):
    """Fetch a single ticket by id. Returns 404 if it doesn't exist."""
    return _row_to_ticket(ticket_id)


@app.patch("/api/tickets/{ticket_id}", response_model=TicketOut, tags=["tickets"])
def update_ticket(ticket_id: int, update: TicketUpdate):
    """
    Partially update a ticket (status, priority, assignee).
    Returns 422 if body is empty; 404 if the ticket doesn't exist.
    """
    raw = update.model_dump(exclude_none=True)
    if not raw:
        raise HTTPException(
            status_code=422,
            detail="Provide at least one field: status, priority, or assignee.",
        )

    # Convert enum values to strings for storage
    fields = {
        k: (v.value if isinstance(v, (Status, Priority)) else v)
        for k, v in raw.items()
    }
    fields["updated_at"] = _now_iso()

    # Build SET clause: "col1 = :col1, col2 = :col2"
    set_clause = ", ".join(f"{col} = :{col}" for col in fields)
    fields["ticket_id"] = ticket_id

    with db_conn() as conn:
        result = conn.execute(
            text(f"UPDATE tickets SET {set_clause} WHERE id = :ticket_id"),
            fields,
        )
        if result.rowcount == 0:
            raise HTTPException(status_code=404, detail=f"Ticket {ticket_id} not found.")

    return _row_to_ticket(ticket_id)


@app.delete("/api/tickets/{ticket_id}", status_code=204, tags=["tickets"])
def delete_ticket(ticket_id: int):
    """Permanently delete a ticket. Returns 204 on success; 404 if not found."""
    with db_conn() as conn:
        result = conn.execute(
            text("DELETE FROM tickets WHERE id = :id"),
            {"id": ticket_id},
        )
        if result.rowcount == 0:
            raise HTTPException(status_code=404, detail=f"Ticket {ticket_id} not found.")
